name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List workspace files
        run: |
          echo "=== Lista de arquivos no workspace ==="
          ls -R .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t devops-toolkit:ci .

      - name: Run scripts in container
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/logs:/opt/scripts/logs" \
            devops-toolkit:ci \
            bash -c "./disk_alert.sh && ./disk_usage_report.sh"

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: script-logs
          path: logs/

